{
	"name":"ProfilerCtrl",
	"version":"1.0.0",
	"core":"core.php",
	"prePHP":"pre.php",
	"loadPHP":"load.php",
	"postPHP":"post.php",
	"db":"db.php",
	"preJS":"pre.js",
	"loadJS":"load.js",
	"postJS":"post.js"
}